services:
  - docker
dist: xenial
language: generic
script:
  - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
  - python3 -VV
  - pip -V
before_deploy:
  - python -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install --user awscli
  - python3 -m pip install --user awsebcli
  - export PATH=$PATH:$HOME/.local/bin
env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH
deploy: 
  provider: script
  skip_cleanup: true
  on:
    branch: main
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
