FROM node:10.15
RUN npm install -g webpack
WORKDIR /usr/src/app
ENV ACCESS_TOKEN_SECRET=jklsdfe993asdfjkl35jklasdfk9
ENV ACCESS_TOKEN_LIFE=120
ENV REFRESH_TOKEN_SECRET=lkjlkljklkjj78sdf299sdfhjk23kasdf8
ENV REFRESH_TOKEN_LIFE=86400
ENV SALT_ROUNDS=10
COPY package*.json /usr/src/app
RUN npm install
EXPOSE 3000



