version: "3.0"
services:
  dev:
    image: backyardcasino/bc-dev:latest
    container_name: "bc-dev-hot"
    environment: 
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}
      - REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
    ports: 
      - "8080:8080"
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    depends_on: 
      - postgres-db
  postgres-db:
    image: backyardcasino/bc-postgres:latest
    container_name: "bc-database"
    environment: 
      - POSTGRES_PASSWORD=bcpw
      - POSTGRES_USER=bcadmin
      - POSTGRES_DB=bcdb
    volumes: 
      - dev-db-volume:/var/lib/postgresql/database
volumes:
  node_modules:
  dev-db-volume: